version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: memoria-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - frontend
      - backend
  frontend:
    container_name: memoria-frontend
    build:
      context: ./frontend
      args:
        # Build-time environment variables for Vite
        - VITE_API_URL=${VITE_API_URL:-/api}
    ports:
      - "6661:3000"
    # environment:
    # - VITE_API_URL=http://backend:8080

  backend:
    container_name: memoria-backend
    build: ./backend
    ports:
      - "6662:8080"
    depends_on:
      - db
    environment:
      - MEMORIA_DB_HOST=db
      - MEMORIA_DB_PORT=5432
      - MEMORIA_DB_USER=postgres
      - MEMORIA_DB_PASSWORD=yourpassword
      - MEMORIA_DB_NAME=memoriadb
      # Allow requests from Nginx
      - MEMORIA_AUTH_ALLOWED_ORIGINS=http://localhost:80
    # volumes:
    # - ./temp_config:/app/config
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=memoriadb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
